name: Benchmark

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  performance:
    name: Performance Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install databases and dependencies
        run: ./setup.sh

      - name: Run benchmark
        run: ./run.sh
