name: Performance Test - Dispatch
on:
  workflow_dispatch:
    inputs:
      dataset:
        type: choice
        description: "Dataset to benchmark"
        required: true
        default: "inat2017"
        options: ["all", "inat2017", "random", "grid", "cluster"]
      count:
        type: number
        description: "Number of points to benchmark"
        required: true
        default: 100000
      repeat:
        type: number
        description: "Number of times to repeat the benchmark"
        required: true
        default: 1

jobs:
  performance-all:
    strategy:
      matrix:
        dataset: ["inat2017", "random", "grid", "cluster"]
    name: Performance Test - All - ${{ matrix.dataset }}
    runs-on: ubuntu-latest
    if: inputs.dataset == 'all'

    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        run: ./setup.sh

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Run benchmark
        run: npm run start -- -t ${{ matrix.dataset }} -c ${{ inputs.count }} -r ${{ inputs.repeat }}

      - name: Upload Result
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.dataset }}-result
          path: results
          retention-days: 1

  performance-single:
    name: Performance Test - ${{ inputs.dataset }}
    runs-on: ubuntu-latest
    if: inputs.dataset != null && inputs.dataset != 'all'

    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        run: ./setup.sh

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Run benchmark
        run: npm run start -- -t ${{ inputs.dataset }} -c ${{ inputs.count }} -r ${{ inputs.repeat }}

      - name: Upload Result
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.dataset }}-result
          path: results
          retention-days: 1
